apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cvat.labels" . | nindent 4 }}
    app: cvat-app
    tier: backend
spec:
  selector:
    app: cvat-app
    tier: backend
    {{- include "cvat.labels" . | nindent 4 }}
  {{- with .Values.cvat.backend.service }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
