#
# Copyright (C) 2018-2020 Intel Corporation
#
# SPDX-License-Identifier: MIT
#
version: '3.3'

services:
  cvat_ci:
    image: cvat_ci
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile.ci
    depends_on:
      - cvat
    environment:
      COVERALLS_SERVICE_NAME:
      CONTAINER_COVERAGE_DATA_DIR:
      GITHUB_ACTIONS:
      GITHUB_TOKEN:
      GITHUB_WORKSPACE:
      GITHUB_REF:
      GITHUB_HEAD_REF:
      GITHUB_RUN_ID:
    volumes:
      - ${HOST_COVERAGE_DATA_DIR}:${CONTAINER_COVERAGE_DATA_DIR}
