{{- if .Values.cvat.opa.defaultStorage.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-opa-rules
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cvat.labels" . | nindent 4 }}
    app: cvat-app
    tier: opa
{{- if semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion }}
immutable: true
{{- end }}
binaryData:
  rules.tar.gz: |-
    {{ .Files.Get "rules.tar.gz" | b64enc }}
{{- end}}